language: node_js
script:
- npm run build
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: mphartman@me.com
  password:
    secure: U+CAjXO+LQyETWqOdGjBHzYHY95NefDcHivmCR+1INzEF6WDlrZBKLdDlJVjewj5lYUX1+d6jYcXg4QlcFIRwHzFLpYJ5GYBYyVQbjDqwV50niAyuidnxmp2AbH+JKzvrw3dYEHArlkwTsdtyQ98i1eGPZC2UCikJ0UxBA1Zh1Yy2rQxIJUL+jgYEr1kI4CoTt/XD7pMEuGTb2bjGOccMMYMe+ttimFLvH4/5jN9pFEK9/Mec5+eM79wlKAlLgkT+o3XQ+TVSXM0dmzrxikj9sp7aniA832bSc3R6f0kJuHMaXMkfquta7lR8Cc1i9MeMq1QWIj1dxYyvm93LHU84k9gHpSI6vgylnMwRmRq/YPpIDFd2gxR3SZPhl1sQ5gl2hlI9UJwuRiTq5dEZ2PZQG6z5/+44i3And+Akvgxs86b/XBdMNNkIrZILSiKp5Dsg6Mjz1eTF0sEY7uDS3hMOmGv8F065S3vMevpu13qkhCrk7KxJIyEuACQHkVg4O268nu0EDckkCdA9xssJGJlE2csjhsTsFtUwNy9HCJQfWUgSr0fVNHpUZ3GdUeLD8jpWqX+r6WgEhq0cRrG7m3SqKqhMIZMrQQEbChRNYfVcWLHZbgEJgwSOuJTJ45WHgaZ6+XjgisbXAUhjdzoeWjAjUpyz55jaLzorJocPPTq/N0=
  organization: waterdeep
  space: development
  on:
    repo: mphartman/adventureland-ui-react
    branch: master
