language: node_js
script:
- npm run build
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: mphartman@me.com
  password:
    secure: Hq4/8EW0ASMuQ2AURP7PQzm0l2aFIAKpnfgi4xJPG2rRTkTQMbOSfXdOEi+nBxGxFfU3O1RXz7DDVUBgHCQ04fzrJCbx0hACgUsUzh+0Ln5x0N/UaO+t2SkPu1RdPZZ2AL+0Wsm0u0ashdVMIDacI3rGoiY6CLTpbqLb4PC4gRKgJ5xzOZVpgAVDFwFhdw6OQmypfHrWX4GfwADDZiJXA7ddpKAAVutVCMeGL7tWjjkZ30QZBDvTqGTnZzmVZnPLGsk77KOTUixsC8DzzfLmNMoT/3HbGg0ApPszbKRQmfhP/Z7yg2Zhsx7UUVRnD/Hc0pvb22VGM1J6qioZ17SdqVkCU6wJUb32qxlEKnxJKhM2YCKHJqT6BvL8FcO4ZT0bgyBobRWfmQCtIdi3O71d3kXXCVK7VKjma/FUp4xagU5MCZof2ndb+plD9f9jJ79PC/Mxzlas8sYdqx/qAbj7ePLsb0C59GPgqVyYCfG+T7z+v5nPCr0eyw9TKeZt8QmQnNrxuVXizntp1xVQyMCt92T7pGrWQV1m/aOEc8pMjQghEe3Mk1G5Z+/GjYbPeVRY1x3cA5EJbL4SrHn+7yG3IM/VLgryJ7/lFORrniYPz4qWzw06al6jd9+NK4p4IYO1F1eFDDDzakQuwEZ5NOU/TgDsC+Jm2zl/ZRQEfzyxyag=
  organization: waterdeep
  space: development
  on:
    repo: mphartman/adventureland-ui-react
    branch: master