language: node_js
script:
  - npm run build
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: mphartman@me.com
  password:
    secure: wGV8kHnCFCtRWvO7a9YFWogI5FsJvLZHJdzT+3frOPQ+WSB/aMtMuYvcbTe9lQMWImY66RXMzpvR0lB5XOxzTArEmLfF3gKgOHhyiKbrZ3Jxhn2v+v1nKXa5puCtwTEPZH/T2VQScq/he9K85bg1CvZb5pyyP6+yorE7kE0cAeEhC9XdhaLzG3NN0A926doPiRNdP2n3R9dcmmECFMup3myKBs/MKa7LoVzvN0yiiuocZwYX5AunT4aIVXqUTW43g0Qst5yxX+gPkdENQXnQNS+kuySMeoeM9QlkS/GxeR3sZxbcPQjZW0vin/F7fr8dg7AJMz4G5pX8WTeir8u5SWZnYM32LMbjJQIFHbwq5JtIBP19hrx1tbvQaILrsAYHMFJDv80UQRi76t9wifBo4jDzLey8JYgCXE4Y9FdYcyaUKKui0LfrdySdx1BCSyLLtTUu82/H0EewHZgeoAbvnYNn0OnjYxXLb3pIrSlV+UY0tQLuny2O6+2WHtDmTwqu5YbnLC5fkdsuaa/0NcHaT7sgPZF+qcB0VuB/LFj1Qs0AAD52czN5GNZIm3Sj/FEhNYj+BZGgEDqf2Cu7Ak6wyAJvr4XnS+jUJjfcaB7MUK8GGEY+lajKHs9I5hT2yAZIGEV1z/Qn8K9ihrrSUNvA2jXJb0EOfWY8UDM06VoaDQI=
  organization: waterdeep
  space: development
  on:
    repo: mphartman/adventureland-ui-react
    branch: master