language: node_js
script:
- npm run build
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: mphartman@me.com
  password:
    secure: aoGd2FOAoeFWnpNI2npHq5Oi3fcSIwLoQTRs2shScNLWAn2f78RFDW/X8IaWWKKKbS2vl4zeLNAcKt1e5qXgLRTXFFZMGRGdlM7WQsjKBUoltR/XqMpNBoj0FnUFUi0mH/Me2kwXzFt6Ca35IhCGphOopj+H5rzKgQSmx9qOiObIUljMOZqTs0ei0MYfkd8oXK/UXN1e9vmLxG3Bg9QYz0TJgntLOZmklns1askqN7nKbLhuyM2++mX2Z435WShKPrhJrAJJIjy88/ZxyZvmXd6mHjQqp24EToTvaOZpgc+APyqzOoz0YuALE67KdAQMbhGpg6n9VsX/GNFGw5Uu4dDJBSHIKHNNHrCXh8bE/+muG0Q8sG5pET4otSdA9LX9E7e332mWG6OaThZ0xqzhOqFJfBgAMp4RJ2mnRwXZdF5bXPPfD3M7r1UGnIien5JVkRnbG751/pX2roUl+TgF/VIVrckTLerMPxNKCK67UQ14CB1513fqDGE1tPEhwanvQa2BUr7JgAC2aXXN/gPaIRvo/RnfhE8wMKEErVcd42UwpDoKTsXc5ng3YTwRHRk3mQJWajsz8Vfm96hitDjKfRUZV75GdiIFvN30Lrs7PS3m2UuvGgTaziXQZioyJ1L5Hcc7mxIDs7GrFmsHrrP2AA9XvpmOX7qZCZyIS2tWnyI=
  organization: waterdeep
  space: development
  on:
    repo: mphartman/adventureland-ui-react
    branch: master
